name: tests

on:
  pull_request:
    branches: [main]
    paths:
      - "oakstore/**"
      - "tests/**"
      - "testing/**"
      - "setup.cfg"
      - "setup.py"
      - "requirements-dev.txt"
      - ".github/workflows/tests.yaml"
  push:
    branches: [main]

jobs:
  tests:
    name: run tests for oakstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install dependencies
        run: pip install -e . -r requirements-dev.txt

      - name: run pytest
        run: pytest .
